### ISSUE TITLE
accompanying dbps server configuration

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-dbpedia-spotlight-wrapper#3]
A couple of suggestions to improve the server configuration of the app. 

1. currently the app hardcodes the address of the dbps server 
https://github.com/clamsproject/app-dbpedia-spotlight-wrapper/blob/f8cdb11c3d9e9c7679faef1676ef9792ca58b12d/app.py#L19
But I think if we can add CLI arguments to change the address at runtime. (keeping `localhost:2222` as the default)

2. dbps server takes some time to be completely ready to serve. So in the `__init__`, we could add a "timeout" `while` loop to wait for the server to send back some empty response. (soemthing like https://stackoverflow.com/questions/54634125/how-to-wait-for-a-specific-http-response-in-python)
https://github.com/clamsproject/app-dbpedia-spotlight-wrapper/blob/f8cdb11c3d9e9c7679faef1676ef9792ca58b12d/app.py#L17-L20

**Comment by wricketts** [comment]
@keighrim 
I pushed some code to a development branch for this, but I have questions/blocks:

1. I made a separate cli argument `--dbps_port` for specifying the port for the spotlight server. Is that correct, or should the `--port` option take two inputs (e.g. `5000` and `2222`)?
2. Right now calling `requests.get` on the default `self.address` gives a Response with error code 400. The content says there is an input exception: `InputException: No input was specified in the &text nor the &url parameter.No input was specified in the &text nor the &url parameter.org.dbpedia`.  I'm not sure why. Isn't there a way to check for the server to be ready without posting text?

**Comment by keighrim** [comment]
> 1. I made a separate cli argument `--dbps_port` for specifying the port for the spotlight server. Is that correct, or should the `--port` option take two inputs (e.g. `5000` and `2222`)?

I think one string argument that can take dbps hostname and port together should be enough. (e.g. `--dbps-address localhost:20202`). BTW conventionally, usually we use dashes instead of underscores in argument option names in shell CLI programming. 

> 2. Right now calling `requests.get` on the default `self.address` gives a Response with error code 400. The content says there is an input exception: `InputException: No input was specified in the &text nor the &url parameter.No input was specified in the &text nor the &url parameter.org.dbpedia`.  I'm not sure why. Isn't there a way to check for the server to be ready without posting text?

I believe that the dbps server returns 400 response because you didn't passed any "text" input to process (using `&text=` part of the request URL). That said, it looks like you actually need to wait for that 400 response in the timeout loop? If you want to be even more specific, you can parse the response body and check for a string match `No input was specified in the &text` to make sure the response you get is actually what you want.

**Comment by wricketts** [comment]
@keighrim I pushed more updates.

1. I think the first issue should be fixed now.
2. In the `__init__` I call `self.session.get(url=self.address, timeout=500)`. Do you think using that timeout parameter would solve this? Or is it better to use the other helper method?
